

== Mapping Methodology

Developing mappings for eForms still follows the https://docs.ted.europa.eu/SWS/mapping_suite/methodology.html[sound principles of conceptual agreement followed by technical implementation], divided into the distinct stages of _conceptual mapping_ ( CM ) using a dialect of https://www.w3.org/TR/sparql11-property-paths/[SPARQL Path] patterns, and _technical mapping_ ( TM ) using the https://rml.io/[RML mapping language].

=== eForms SDK Field Definitions

In contrast to SF, which had https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas-archive[XSD schemas] as the only cue for the underlying model, there is an https://github.com/OP-TED/eForms-SDK[eForms SDK] which prescribes eForm XML element https://developer.mozilla.org/en-US/docs/Web/XPath[XPaths] in terms of nodes and fields, which lends an easier framework for the management and comprehension of the http://docs.oasis-open.org/ubl/os-UBL-2.3/UBL-2.3.html[UBL]-based XML model behind elements used across the eForm notices. The notices themselves are categorized under https://docs.ted.europa.eu/eforms/latest/schema/documents-forms-and-notices.html[document, form and notice types and subtypes], such as Competition Notice, subtype 16 (EF16).

=== Mapping Groups

A new idea introduced into the mapping methodology is the notion of a Mapping Group (MG), which is a representation of RDF connections (relationships) and subject groupings in a simple, hyphen-delimited textual notation, in the form:

```
MG-{TrailingClass}-{intermediateClassAndPropertyPath}-{RootClass}
```

where, for example, the full path of an organisation's address might be:

```
MG-Address-hasAddress-Location-hasLocation-Organization
```

This serves to provide an indication of how RDF statements are logically grouped together to form the right (connected) instances, given that data for a given subject may be spread across completely different XPaths in the source XML. That is why, in the technical mapping, MGs are used to form the subject URIs of the RML rules (TriplesMaps), suffixed with the node name (as per the SDK) where the information comes from, for example:

```
tedm:MG-Address-hasAddress-Location-hasLocation-Organization_ND-Company a rr:TriplesMap
```

Different nodes usually require different subject templates or iterators, especially those which are located at entirely different or _orthogonal_ XPaths, requiring as many RML TriplesMaps with the same MG but different node names.
