

== Mapping Methodology

Developing mappings for eForms still follows the https://docs.ted.europa.eu/SWS/mapping_suite/methodology.html[sound principles of conceptual agreement followed by technical implementation], divided into the distinct stages of _conceptual mapping_ ( CM ) using a dialect of https://www.w3.org/TR/sparql11-property-paths/[SPARQL Path] patterns, and _technical mapping_ ( TM ) using the https://rml.io/[RML mapping language].

=== eForms SDK Field Definitions

In contrast to SF, which had https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas-archive[XSD schemas] as the only cue for the underlying model, there is an https://github.com/OP-TED/eForms-SDK[eForms SDK] which prescribes eForm XML element https://developer.mozilla.org/en-US/docs/Web/XPath[XPaths] in terms of nodes and fields, which lends an easier framework for the management and comprehension of the http://docs.oasis-open.org/ubl/os-UBL-2.3/UBL-2.3.html[UBL]-based XML model behind elements used across the eForm notices. The notices themselves are categorized under https://docs.ted.europa.eu/eforms/latest/schema/documents-forms-and-notices.html[document, form and notice types and subtypes], such as Competition Notice, subtype 16 (EF16).

=== Mapping Groups

A new idea introduced into the mapping methodology is the notion of a Mapping Group (MG), which is a representation of RDF connections (relationships) and subject groupings in a simple, hyphen-delimited textual notation, in the form:

```
MG-{TrailingClass}-{intermediateClassAndPropertyPath}-{RootClass}
```

where, for example, the full path of an organisation's address might be:

```
MG-Address-hasAddress-Location-hasLocation-Organization
```

This serves to provide an indication of how RDF statements are logically grouped together to form the right (connected) instances, given that data for a given subject may be spread across completely different XPaths in the source XML. That is why, in the technical mapping, MGs are used to form the subject URIs of the RML rules (TriplesMaps), suffixed with the node name (as per the SDK) where the information comes from, for example:

```
tedm:MG-Address-hasAddress-Location-hasLocation-Organization_ND-Company a rr:TriplesMap
```

Different nodes usually require different subject templates or iterators, especially those which are located at entirely different or _orthogonal_ XPaths, requiring as many RML TriplesMaps with the same MG but different node names.


=== RDF URI Scheme

The eForms RML mappings use the following URI scheme for the representing ePO ontology instances:

```
{ns}id_{notice-id}_{concept}_{trailer}
```

, where:

* `{ns}` is a base namespace, in this case
`http://data.europa.eu/a4g/resource/`
* `{concept}` is either (i) an ontology fragment label or (ii) source
element label, with a suffix or prefix
* `{trailer}` is either (i) an ID value (if the resource has one) or
(ii) an _online_ computed, deterministic hash
* Root concepts such as `epo:Notice` end up to only the `{concept}`

Expanding on some of the components for further clarity:

* Whether a `concept` is an ontology fragment or source element label,
and whether this label has a suffix (rarely) or prefix, depends on the
subjective (human) evaluation of whether only having the class name is
sufficient hint of what the URI represents.
* The trailer, when a hash, is computed (seeded) with the XPath named
element (e.g. `cbc:ID`) or (often relative) path (e.g. `path(cbc:ID)`)
of what is being mapped, and therefore lends a unique identity to the
URI. This yields reproducible URIs across RML TripleMaps, in case a
resource needed to be instantiated at different XPaths, for whatever
purpose.
** A Lot or any other resource with an inherent ID, would simply have
its `cbc:ID` value as the trailer, for
e.g. `epd:id_14549263-b47b-4e59-96a1-2d0d13e19343_Lot_LOT-0001`, which
is very useful for linking purposes at orthogonal XPaths (e.g. wherever
an `id-ref` is concerned, that ID could simply be used to produce a
linkable URI without having to navigate XPaths).
** Any other resource where there is no inherent ID would have a hash
that is unique to the XPath it represents, e.g. an `epo:Purpose`
instance, if instantiated at different XPaths for associating different
attributes, would have the same URI across those instantiations,
resulting in one unique instance and no duplication due to multiple
mappings.
*** The `adms:Identifier`, although having an ID, may still get a hash
instead of ID in its trailer, as it may not have a short ID that is
sensible to use/read (however we may not have enforced this rule
strongly)

**Note:** Wherever _URI_ is mentioned,
https://www.w3.org/2001/Talks/0912-IUC-IRI/paper.html#:~:text=In%20principle%2C%20the%20definition%20of,us%2Dascii%20characters%20in%20URIs[IRI]
is meant. Also, the generation of hashes is done _online_ against a
remote HTTP web API endpoint offering this function, during
transformation (which can otherwise be an offline process).